### PR TITLE
Create backend.tf

### PR DESCRIPTION
**Pull request by udienz**

### CODE REVIEW

**Comment by udienz** [comment]
atlantis plan

**Comment by cakbrod** [comment]
Ran Plan for 0 projects:

**Comment by cakbrod** [comment]
Ran Plan for 3 projects:

1. project: `production-environment` dir: `production` workspace: `default`
1. project: `qa-environment` dir: `qa` workspace: `default`
1. project: `staging-environment` dir: `staging` workspace: `default`

### 1. project: `production-environment` dir: `production` workspace: `default`
<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.production-udienz_id-blog will be created
+ resource "null_resource" "production-udienz_id-blog" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_id-ftp will be created
+ resource "null_resource" "production-udienz_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_id-mail will be created
+ resource "null_resource" "production-udienz_id-mail" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_id-www will be created
+ resource "null_resource" "production-udienz_id-www" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_id-www_1 will be created
+ resource "null_resource" "production-udienz_id-www_1" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_my_id-blog will be created
+ resource "null_resource" "production-udienz_my_id-blog" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_my_id-ftp will be created
+ resource "null_resource" "production-udienz_my_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_my_id-mail will be created
+ resource "null_resource" "production-udienz_my_id-mail" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_my_id-www will be created
+ resource "null_resource" "production-udienz_my_id-www" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_web_id-blog will be created
+ resource "null_resource" "production-udienz_web_id-blog" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_web_id-ftp will be created
+ resource "null_resource" "production-udienz_web_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_web_id-mail will be created
+ resource "null_resource" "production-udienz_web_id-mail" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_web_id-www will be created
+ resource "null_resource" "production-udienz_web_id-www" {
      + id = (known after apply)
    }

Plan: 13 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p production-environment`
* :put_litter_in_its_place: To **delete** this plan click [here](http://ubuntu-s-do-sgp-1:8081/lock?id=udienz%252Fterraform%252Fproduction%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p production-environment`
</details>
Plan: 13 to add, 0 to change, 0 to destroy.

---
### 2. project: `qa-environment` dir: `qa` workspace: `default`
<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.qa-udienz_id-blog will be created
+ resource "null_resource" "qa-udienz_id-blog" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_id-ftp will be created
+ resource "null_resource" "qa-udienz_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_id-mail will be created
+ resource "null_resource" "qa-udienz_id-mail" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_id-www will be created
+ resource "null_resource" "qa-udienz_id-www" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_id-wwwa will be created
+ resource "null_resource" "qa-udienz_id-wwwa" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_my_id-blog will be created
+ resource "null_resource" "qa-udienz_my_id-blog" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_my_id-ftp will be created
+ resource "null_resource" "qa-udienz_my_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_my_id-mail will be created
+ resource "null_resource" "qa-udienz_my_id-mail" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_my_id-www will be created
+ resource "null_resource" "qa-udienz_my_id-www" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_web_id-blog will be created
+ resource "null_resource" "qa-udienz_web_id-blog" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_web_id-ftp will be created
+ resource "null_resource" "qa-udienz_web_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_web_id-mail will be created
+ resource "null_resource" "qa-udienz_web_id-mail" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_web_id-www will be created
+ resource "null_resource" "qa-udienz_web_id-www" {
      + id = (known after apply)
    }

Plan: 13 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p qa-environment`
* :put_litter_in_its_place: To **delete** this plan click [here](http://ubuntu-s-do-sgp-1:8081/lock?id=udienz%252Fterraform%252Fqa%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p qa-environment`
</details>
Plan: 13 to add, 0 to change, 0 to destroy.

---
### 3. project: `staging-environment` dir: `staging` workspace: `default`
<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.staging-udienz_id-blog will be created
+ resource "null_resource" "staging-udienz_id-blog" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_id-ftp will be created
+ resource "null_resource" "staging-udienz_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_id-mail will be created
+ resource "null_resource" "staging-udienz_id-mail" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_id-www will be created
+ resource "null_resource" "staging-udienz_id-www" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_id-www_1 will be created
+ resource "null_resource" "staging-udienz_id-www_1" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_my_id-blog will be created
+ resource "null_resource" "staging-udienz_my_id-blog" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_my_id-ftp will be created
+ resource "null_resource" "staging-udienz_my_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_my_id-mail will be created
+ resource "null_resource" "staging-udienz_my_id-mail" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_my_id-www will be created
+ resource "null_resource" "staging-udienz_my_id-www" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_web_id-blog will be created
+ resource "null_resource" "staging-udienz_web_id-blog" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_web_id-ftp will be created
+ resource "null_resource" "staging-udienz_web_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_web_id-mail will be created
+ resource "null_resource" "staging-udienz_web_id-mail" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_web_id-www will be created
+ resource "null_resource" "staging-udienz_web_id-www" {
      + id = (known after apply)
    }

Plan: 13 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p staging-environment`
* :put_litter_in_its_place: To **delete** this plan click [here](http://ubuntu-s-do-sgp-1:8081/lock?id=udienz%252Fterraform%252Fstaging%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p staging-environment`
</details>
Plan: 13 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by udienz** [comment]
atlantis apply

**Comment by cakbrod** [comment]
Ran Apply for 3 projects:

1. project: `production-environment` dir: `production` workspace: `default`
1. project: `qa-environment` dir: `qa` workspace: `default`
1. project: `staging-environment` dir: `staging` workspace: `default`

### 1. project: `production-environment` dir: `production` workspace: `default`
<details><summary>Show Output</summary>

```diff
null_resource.production-udienz_web_id-ftp: Creating...
null_resource.production-udienz_id-www_1: Creating...
null_resource.production-udienz_id-www: Creating...
null_resource.production-udienz_my_id-blog: Creating...
null_resource.production-udienz_web_id-mail: Creating...
null_resource.production-udienz_my_id-blog: Creation complete after 0s [id=7537794686909852368]
null_resource.production-udienz_my_id-ftp: Creating...
null_resource.production-udienz_my_id-mail: Creating...
null_resource.production-udienz_web_id-www: Creating...
null_resource.production-udienz_id-mail: Creating...
null_resource.production-udienz_id-ftp: Creating...
null_resource.production-udienz_web_id-mail: Creation complete after 0s [id=2817750826941044336]
null_resource.production-udienz_web_id-ftp: Creation complete after 0s [id=6621620212074547252]
null_resource.production-udienz_id-www_1: Creation complete after 0s [id=646079458992141309]
null_resource.production-udienz_id-www: Creation complete after 0s [id=3114400977155267976]
null_resource.production-udienz_my_id-ftp: Creation complete after 0s [id=821316287895500359]
null_resource.production-udienz_my_id-mail: Creation complete after 0s [id=7003299643851419309]
null_resource.production-udienz_web_id-www: Creation complete after 0s [id=1113802524966630217]
null_resource.production-udienz_id-mail: Creation complete after 0s [id=2578113964690703479]
null_resource.production-udienz_id-ftp: Creation complete after 0s [id=8887757411081324734]
null_resource.production-udienz_id-blog: Creating...
null_resource.production-udienz_my_id-www: Creating...
null_resource.production-udienz_web_id-blog: Creating...
null_resource.production-udienz_my_id-www: Creation complete after 0s [id=3775184791372911208]
null_resource.production-udienz_web_id-blog: Creation complete after 0s [id=3019541112633655255]
null_resource.production-udienz_id-blog: Creation complete after 0s [id=3981208444010016015]

Apply complete! Resources: 13 added, 0 changed, 0 destroyed.
```

</details>

---
### 2. project: `qa-environment` dir: `qa` workspace: `default`
**Apply Error**
```
running "/usr/bin/terraform apply -input=false \"/home/atlantis/.atlantis/repos/udienz/terraform/9/default/qa/qa-environment-default.tfplan\"" in "/home/atlantis/.atlantis/repos/udienz/terraform/9/default/qa": exit status 1
╷
│ Error: Saved plan is stale
│ 
│ The given plan file can no longer be applied because the state was changed
│ by another operation after the plan was created.
╵

```

---
### 3. project: `staging-environment` dir: `staging` workspace: `default`
**Apply Error**
```
running "/usr/bin/terraform apply -input=false \"/home/atlantis/.atlantis/repos/udienz/terraform/9/default/staging/staging-environment-default.tfplan\"" in "/home/atlantis/.atlantis/repos/udienz/terraform/9/default/staging": exit status 1
╷
│ Error: Saved plan is stale
│ 
│ The given plan file can no longer be applied because the state was changed
│ by another operation after the plan was created.
╵

```

---

**Comment by udienz** [comment]
atlantis apply

**Comment by cakbrod** [comment]
Ran Apply for 2 projects:

1. project: `qa-environment` dir: `qa` workspace: `default`
1. project: `staging-environment` dir: `staging` workspace: `default`

### 1. project: `qa-environment` dir: `qa` workspace: `default`
**Apply Error**
```
running "/usr/bin/terraform apply -input=false \"/home/atlantis/.atlantis/repos/udienz/terraform/9/default/qa/qa-environment-default.tfplan\"" in "/home/atlantis/.atlantis/repos/udienz/terraform/9/default/qa": exit status 1
╷
│ Error: Saved plan is stale
│ 
│ The given plan file can no longer be applied because the state was changed
│ by another operation after the plan was created.
╵

```

---
### 2. project: `staging-environment` dir: `staging` workspace: `default`
**Apply Error**
```
running "/usr/bin/terraform apply -input=false \"/home/atlantis/.atlantis/repos/udienz/terraform/9/default/staging/staging-environment-default.tfplan\"" in "/home/atlantis/.atlantis/repos/udienz/terraform/9/default/staging": exit status 1
╷
│ Error: Saved plan is stale
│ 
│ The given plan file can no longer be applied because the state was changed
│ by another operation after the plan was created.
╵

```

---

**Comment by cakbrod** [comment]
Ran Plan for 3 projects:

1. project: `production-environment` dir: `production` workspace: `default`
1. project: `qa-environment` dir: `qa` workspace: `default`
1. project: `staging-environment` dir: `staging` workspace: `default`

### 1. project: `production-environment` dir: `production` workspace: `default`
<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.production-udienz_id-blog will be created
+ resource "null_resource" "production-udienz_id-blog" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_id-ftp will be created
+ resource "null_resource" "production-udienz_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_id-mail will be created
+ resource "null_resource" "production-udienz_id-mail" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_id-www will be created
+ resource "null_resource" "production-udienz_id-www" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_id-www_1 will be created
+ resource "null_resource" "production-udienz_id-www_1" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_my_id-blog will be created
+ resource "null_resource" "production-udienz_my_id-blog" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_my_id-ftp will be created
+ resource "null_resource" "production-udienz_my_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_my_id-mail will be created
+ resource "null_resource" "production-udienz_my_id-mail" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_my_id-www will be created
+ resource "null_resource" "production-udienz_my_id-www" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_web_id-blog will be created
+ resource "null_resource" "production-udienz_web_id-blog" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_web_id-ftp will be created
+ resource "null_resource" "production-udienz_web_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_web_id-mail will be created
+ resource "null_resource" "production-udienz_web_id-mail" {
      + id = (known after apply)
    }

  # null_resource.production-udienz_web_id-www will be created
+ resource "null_resource" "production-udienz_web_id-www" {
      + id = (known after apply)
    }

Plan: 13 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p production-environment`
* :put_litter_in_its_place: To **delete** this plan click [here](http://ubuntu-s-do-sgp-1:8081/lock?id=udienz%252Fterraform%252Fproduction%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p production-environment`
</details>
Plan: 13 to add, 0 to change, 0 to destroy.

---
### 2. project: `qa-environment` dir: `qa` workspace: `default`
<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.qa-udienz_id-blog will be created
+ resource "null_resource" "qa-udienz_id-blog" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_id-ftp will be created
+ resource "null_resource" "qa-udienz_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_id-mail will be created
+ resource "null_resource" "qa-udienz_id-mail" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_id-www will be created
+ resource "null_resource" "qa-udienz_id-www" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_id-wwwa will be created
+ resource "null_resource" "qa-udienz_id-wwwa" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_my_id-blog will be created
+ resource "null_resource" "qa-udienz_my_id-blog" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_my_id-ftp will be created
+ resource "null_resource" "qa-udienz_my_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_my_id-mail will be created
+ resource "null_resource" "qa-udienz_my_id-mail" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_my_id-www will be created
+ resource "null_resource" "qa-udienz_my_id-www" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_web_id-blog will be created
+ resource "null_resource" "qa-udienz_web_id-blog" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_web_id-ftp will be created
+ resource "null_resource" "qa-udienz_web_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_web_id-mail will be created
+ resource "null_resource" "qa-udienz_web_id-mail" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_web_id-www will be created
+ resource "null_resource" "qa-udienz_web_id-www" {
      + id = (known after apply)
    }

Plan: 13 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p qa-environment`
* :put_litter_in_its_place: To **delete** this plan click [here](http://ubuntu-s-do-sgp-1:8081/lock?id=udienz%252Fterraform%252Fqa%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p qa-environment`
</details>
Plan: 13 to add, 0 to change, 0 to destroy.

---
### 3. project: `staging-environment` dir: `staging` workspace: `default`
<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.staging-udienz_id-blog will be created
+ resource "null_resource" "staging-udienz_id-blog" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_id-ftp will be created
+ resource "null_resource" "staging-udienz_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_id-mail will be created
+ resource "null_resource" "staging-udienz_id-mail" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_id-www will be created
+ resource "null_resource" "staging-udienz_id-www" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_id-www_1 will be created
+ resource "null_resource" "staging-udienz_id-www_1" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_my_id-blog will be created
+ resource "null_resource" "staging-udienz_my_id-blog" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_my_id-ftp will be created
+ resource "null_resource" "staging-udienz_my_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_my_id-mail will be created
+ resource "null_resource" "staging-udienz_my_id-mail" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_my_id-www will be created
+ resource "null_resource" "staging-udienz_my_id-www" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_web_id-blog will be created
+ resource "null_resource" "staging-udienz_web_id-blog" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_web_id-ftp will be created
+ resource "null_resource" "staging-udienz_web_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_web_id-mail will be created
+ resource "null_resource" "staging-udienz_web_id-mail" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_web_id-www will be created
+ resource "null_resource" "staging-udienz_web_id-www" {
      + id = (known after apply)
    }

Plan: 13 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p staging-environment`
* :put_litter_in_its_place: To **delete** this plan click [here](http://ubuntu-s-do-sgp-1:8081/lock?id=udienz%252Fterraform%252Fstaging%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p staging-environment`
</details>
Plan: 13 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by udienz** [comment]
atlantis apply

**Comment by cakbrod** [comment]
Ran Apply for 3 projects:

1. project: `production-environment` dir: `production` workspace: `default`
1. project: `qa-environment` dir: `qa` workspace: `default`
1. project: `staging-environment` dir: `staging` workspace: `default`

### 1. project: `production-environment` dir: `production` workspace: `default`
<details><summary>Show Output</summary>

```diff
null_resource.production-udienz_web_id-www: Creating...
null_resource.production-udienz_id-www: Creating...
null_resource.production-udienz_my_id-www: Creating...
null_resource.production-udienz_my_id-blog: Creating...
null_resource.production-udienz_web_id-mail: Creating...
null_resource.production-udienz_id-www_1: Creating...
null_resource.production-udienz_id-www_1: Creation complete after 0s [id=4726108566907354026]
null_resource.production-udienz_web_id-blog: Creating...
null_resource.production-udienz_my_id-mail: Creating...
null_resource.production-udienz_id-blog: Creating...
null_resource.production-udienz_id-mail: Creating...
null_resource.production-udienz_web_id-mail: Creation complete after 0s [id=1201831754649735881]
null_resource.production-udienz_web_id-www: Creation complete after 0s [id=790651303675482104]
null_resource.production-udienz_id-www: Creation complete after 0s [id=9185840338987289663]
null_resource.production-udienz_my_id-www: Creation complete after 0s [id=9189882088647030857]
null_resource.production-udienz_my_id-blog: Creation complete after 0s [id=646912857480004099]
null_resource.production-udienz_web_id-blog: Creation complete after 0s [id=7249467706039685468]
null_resource.production-udienz_my_id-mail: Creation complete after 0s [id=2727183470334851238]
null_resource.production-udienz_id-blog: Creation complete after 0s [id=4709002038543611857]
null_resource.production-udienz_id-mail: Creation complete after 0s [id=4417261960177976568]
null_resource.production-udienz_id-ftp: Creating...
null_resource.production-udienz_my_id-ftp: Creating...
null_resource.production-udienz_web_id-ftp: Creating...
null_resource.production-udienz_my_id-ftp: Creation complete after 0s [id=4811900810964652287]
null_resource.production-udienz_web_id-ftp: Creation complete after 0s [id=6944135377538162281]
null_resource.production-udienz_id-ftp: Creation complete after 0s [id=5405520724917953951]

Apply complete! Resources: 13 added, 0 changed, 0 destroyed.
```

</details>

---
### 2. project: `qa-environment` dir: `qa` workspace: `default`
<details><summary>Show Output</summary>

```diff
null_resource.qa-udienz_my_id-www: Creating...
null_resource.qa-udienz_id-ftp: Creating...
null_resource.qa-udienz_my_id-mail: Creating...
null_resource.qa-udienz_web_id-mail: Creating...
null_resource.qa-udienz_web_id-blog: Creating...
null_resource.qa-udienz_web_id-www: Creating...
null_resource.qa-udienz_web_id-blog: Creation complete after 0s [id=3419267814985131725]
null_resource.qa-udienz_id-www: Creating...
null_resource.qa-udienz_id-wwwa: Creating...
null_resource.qa-udienz_my_id-ftp: Creating...
null_resource.qa-udienz_id-mail: Creating...
null_resource.qa-udienz_web_id-www: Creation complete after 0s [id=618338560962332935]
null_resource.qa-udienz_id-ftp: Creation complete after 0s [id=5889129635304101495]
null_resource.qa-udienz_my_id-mail: Creation complete after 0s [id=5964053640992614087]
null_resource.qa-udienz_web_id-mail: Creation complete after 0s [id=2286717520600995326]
null_resource.qa-udienz_my_id-www: Creation complete after 0s [id=3784716704065112864]
null_resource.qa-udienz_my_id-ftp: Creation complete after 0s [id=6261082850762112552]
null_resource.qa-udienz_id-mail: Creation complete after 0s [id=2570436705788982134]
null_resource.qa-udienz_id-www: Creation complete after 0s [id=5499550190871862593]
null_resource.qa-udienz_id-wwwa: Creation complete after 0s [id=1138141563291924910]
null_resource.qa-udienz_web_id-ftp: Creating...
null_resource.qa-udienz_id-blog: Creating...
null_resource.qa-udienz_my_id-blog: Creating...
null_resource.qa-udienz_web_id-ftp: Creation complete after 1s [id=6269301961862685935]
null_resource.qa-udienz_id-blog: Creation complete after 1s [id=993095314404665664]
null_resource.qa-udienz_my_id-blog: Creation complete after 1s [id=2633355403972743967]

Apply complete! Resources: 13 added, 0 changed, 0 destroyed.
```

</details>

---
### 3. project: `staging-environment` dir: `staging` workspace: `default`
<details><summary>Show Output</summary>

```diff
null_resource.staging-udienz_web_id-mail: Creating...
null_resource.staging-udienz_id-ftp: Creating...
null_resource.staging-udienz_web_id-blog: Creating...
null_resource.staging-udienz_id-blog: Creating...
null_resource.staging-udienz_my_id-www: Creating...
null_resource.staging-udienz_my_id-blog: Creating...
null_resource.staging-udienz_my_id-www: Creation complete after 0s [id=5046869434581997233]
null_resource.staging-udienz_web_id-ftp: Creating...
null_resource.staging-udienz_my_id-ftp: Creating...
null_resource.staging-udienz_id-www: Creating...
null_resource.staging-udienz_id-www_1: Creating...
null_resource.staging-udienz_my_id-blog: Creation complete after 0s [id=5788319515534920165]
null_resource.staging-udienz_id-blog: Creation complete after 0s [id=4898030117192878695]
null_resource.staging-udienz_web_id-mail: Creation complete after 0s [id=7356545455360745288]
null_resource.staging-udienz_id-www: Creation complete after 0s [id=185917397749495431]
null_resource.staging-udienz_id-ftp: Creation complete after 0s [id=258007655147433899]
null_resource.staging-udienz_web_id-blog: Creation complete after 0s [id=7626623390847754661]
null_resource.staging-udienz_web_id-ftp: Creation complete after 0s [id=6025554216272630225]
null_resource.staging-udienz_my_id-ftp: Creation complete after 0s [id=2201056147615743052]
null_resource.staging-udienz_id-www_1: Creation complete after 0s [id=3864254345476639192]
null_resource.staging-udienz_my_id-mail: Creating...
null_resource.staging-udienz_web_id-www: Creating...
null_resource.staging-udienz_id-mail: Creating...
null_resource.staging-udienz_web_id-www: Creation complete after 0s [id=9213733156821908299]
null_resource.staging-udienz_id-mail: Creation complete after 0s [id=6596271061652386808]
null_resource.staging-udienz_my_id-mail: Creation complete after 1s [id=3188927280277579023]

Apply complete! Resources: 13 added, 0 changed, 0 destroyed.
```

</details>

---

**Comment by cakbrod** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `production` workspace: `default`
- dir: `qa` workspace: `default`
- dir: `staging` workspace: `default`

**Pull request merged**
