### PR TITLE
Update QA udienz.id-www.tf

### PR DESCRIPTION
**Pull request by udienz**

### CODE REVIEW

**Comment by cakbrod** [comment]
Ran Plan for project: `qa-environment` dir: `qa` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.qa-udienz_id-blog will be created
+ resource "null_resource" "qa-udienz_id-blog" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_id-ftp will be created
+ resource "null_resource" "qa-udienz_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_id-mail will be created
+ resource "null_resource" "qa-udienz_id-mail" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_id-www will be created
+ resource "null_resource" "qa-udienz_id-www" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_id-wwwa will be created
+ resource "null_resource" "qa-udienz_id-wwwa" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_my_id-blog will be created
+ resource "null_resource" "qa-udienz_my_id-blog" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_my_id-ftp will be created
+ resource "null_resource" "qa-udienz_my_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_my_id-mail will be created
+ resource "null_resource" "qa-udienz_my_id-mail" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_my_id-www will be created
+ resource "null_resource" "qa-udienz_my_id-www" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_web_id-blog will be created
+ resource "null_resource" "qa-udienz_web_id-blog" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_web_id-ftp will be created
+ resource "null_resource" "qa-udienz_web_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_web_id-mail will be created
+ resource "null_resource" "qa-udienz_web_id-mail" {
      + id = (known after apply)
    }

  # null_resource.qa-udienz_web_id-www will be created
+ resource "null_resource" "qa-udienz_web_id-www" {
      + id = (known after apply)
    }

Plan: 13 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p qa-environment`
* :put_litter_in_its_place: To **delete** this plan click [here](http://ubuntu-s-do-sgp-1:8081/lock?id=udienz%252Fterraform%252Fqa%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p qa-environment`
</details>
Plan: 13 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by udienz** [comment]
atlantis apply

**Comment by cakbrod** [comment]
Ran Apply for project: `qa-environment` dir: `qa` workspace: `default`

<details><summary>Show Output</summary>

```diff
null_resource.qa-udienz_web_id-blog: Creating...
null_resource.qa-udienz_my_id-blog: Creating...
null_resource.qa-udienz_id-ftp: Creating...
null_resource.qa-udienz_id-mail: Creating...
null_resource.qa-udienz_web_id-mail: Creating...
null_resource.qa-udienz_my_id-www: Creating...
null_resource.qa-udienz_my_id-ftp: Creating...
null_resource.qa-udienz_id-www: Creating...
null_resource.qa-udienz_web_id-www: Creating...
null_resource.qa-udienz_my_id-mail: Creating...
null_resource.qa-udienz_my_id-www: Creation complete after 0s [id=5886103929381065676]
null_resource.qa-udienz_my_id-ftp: Creation complete after 0s [id=354873278994027105]
null_resource.qa-udienz_web_id-blog: Creation complete after 0s [id=9134222660979508830]
null_resource.qa-udienz_my_id-blog: Creation complete after 0s [id=1296690397396238824]
null_resource.qa-udienz_id-ftp: Creation complete after 0s [id=819668092889619840]
null_resource.qa-udienz_id-mail: Creation complete after 0s [id=4884936192711812178]
null_resource.qa-udienz_web_id-mail: Creation complete after 0s [id=1916243398918976502]
null_resource.qa-udienz_my_id-mail: Creation complete after 0s [id=7207725718187549417]
null_resource.qa-udienz_id-www: Creation complete after 0s [id=8714092151381429322]
null_resource.qa-udienz_web_id-www: Creation complete after 0s [id=3078972818183532972]
null_resource.qa-udienz_id-wwwa: Creating...
null_resource.qa-udienz_web_id-ftp: Creating...
null_resource.qa-udienz_id-blog: Creating...
null_resource.qa-udienz_id-blog: Creation complete after 0s [id=2541882733263119807]
null_resource.qa-udienz_web_id-ftp: Creation complete after 0s [id=4044425664197458111]
null_resource.qa-udienz_id-wwwa: Creation complete after 0s [id=2622310516707784015]

Apply complete! Resources: 13 added, 0 changed, 0 destroyed.
```

</details>

**Comment by cakbrod** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `qa` workspace: `default`

**Pull request merged**
