### PR TITLE
Update staging udienz.id-www.tf

### PR DESCRIPTION
**Pull request by udienz**

### CODE REVIEW

**Comment by cakbrod** [comment]
Ran Plan for project: `staging-environment` dir: `staging` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.staging-udienz_id-blog will be created
+ resource "null_resource" "staging-udienz_id-blog" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_id-ftp will be created
+ resource "null_resource" "staging-udienz_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_id-mail will be created
+ resource "null_resource" "staging-udienz_id-mail" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_id-www will be created
+ resource "null_resource" "staging-udienz_id-www" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_id-www_1 will be created
+ resource "null_resource" "staging-udienz_id-www_1" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_my_id-blog will be created
+ resource "null_resource" "staging-udienz_my_id-blog" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_my_id-ftp will be created
+ resource "null_resource" "staging-udienz_my_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_my_id-mail will be created
+ resource "null_resource" "staging-udienz_my_id-mail" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_my_id-www will be created
+ resource "null_resource" "staging-udienz_my_id-www" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_web_id-blog will be created
+ resource "null_resource" "staging-udienz_web_id-blog" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_web_id-ftp will be created
+ resource "null_resource" "staging-udienz_web_id-ftp" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_web_id-mail will be created
+ resource "null_resource" "staging-udienz_web_id-mail" {
      + id = (known after apply)
    }

  # null_resource.staging-udienz_web_id-www will be created
+ resource "null_resource" "staging-udienz_web_id-www" {
      + id = (known after apply)
    }

Plan: 13 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p staging-environment`
* :put_litter_in_its_place: To **delete** this plan click [here](http://ubuntu-s-do-sgp-1:8081/lock?id=udienz%252Fterraform%252Fstaging%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p staging-environment`
</details>
Plan: 13 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by udienz** [comment]
atlantis apply

**Comment by cakbrod** [comment]
Ran Apply for project: `staging-environment` dir: `staging` workspace: `default`

<details><summary>Show Output</summary>

```diff
null_resource.staging-udienz_id-mail: Creating...
null_resource.staging-udienz_id-blog: Creating...
null_resource.staging-udienz_id-www: Creating...
null_resource.staging-udienz_id-www_1: Creating...
null_resource.staging-udienz_my_id-ftp: Creating...
null_resource.staging-udienz_id-www_1: Creation complete after 1s [id=5174420266156113882]
null_resource.staging-udienz_web_id-blog: Creating...
null_resource.staging-udienz_my_id-www: Creating...
null_resource.staging-udienz_web_id-ftp: Creating...
null_resource.staging-udienz_my_id-blog: Creating...
null_resource.staging-udienz_web_id-mail: Creating...
null_resource.staging-udienz_my_id-ftp: Creation complete after 1s [id=7832081099155436863]
null_resource.staging-udienz_id-mail: Creation complete after 1s [id=6667274212579198471]
null_resource.staging-udienz_id-blog: Creation complete after 1s [id=8850487299211987480]
null_resource.staging-udienz_id-www: Creation complete after 1s [id=4926968529482872780]
null_resource.staging-udienz_my_id-blog: Creation complete after 0s [id=5528401198847643052]
null_resource.staging-udienz_web_id-mail: Creation complete after 0s [id=2434736891774345821]
null_resource.staging-udienz_web_id-blog: Creation complete after 0s [id=7092023805062751164]
null_resource.staging-udienz_my_id-www: Creation complete after 0s [id=2136742917252017908]
null_resource.staging-udienz_web_id-ftp: Creation complete after 0s [id=4076905435337344942]
null_resource.staging-udienz_id-ftp: Creating...
null_resource.staging-udienz_my_id-mail: Creating...
null_resource.staging-udienz_id-ftp: Creation complete after 0s [id=8502637366226039562]
null_resource.staging-udienz_web_id-www: Creating...
null_resource.staging-udienz_my_id-mail: Creation complete after 0s [id=835689707916967635]
null_resource.staging-udienz_web_id-www: Creation complete after 0s [id=5691631950873727642]

Apply complete! Resources: 13 added, 0 changed, 0 destroyed.
```

</details>

**Comment by cakbrod** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `staging` workspace: `default`

**Pull request merged**
